// <auto-generated />
using System;
using DepartmentRatingDAL.Models.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DepartmentRatingDAL.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Owner");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new { AdminId = 1, Date = new DateTime(2019, 12, 11, 10, 57, 42, 578, DateTimeKind.Local), Name = "n7701-00-057", Owner = "System" }
                    );
                });

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.EventLog", b =>
                {
                    b.Property<int>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Owner");

                    b.Property<string>("Table");

                    b.HasKey("EventLogId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.Main", b =>
                {
                    b.Property<int>("MainId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("OffenceId");

                    b.Property<string>("Owner");

                    b.Property<int>("UserId");

                    b.HasKey("MainId");

                    b.HasIndex("OffenceId");

                    b.HasIndex("UserId");

                    b.ToTable("Mains");
                });

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.Offence", b =>
                {
                    b.Property<int>("OffenceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Owner");

                    b.HasKey("OffenceId");

                    b.ToTable("Offences");
                });

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account");

                    b.Property<bool>("Enabled");

                    b.Property<string>("Fio");

                    b.Property<int>("Rating");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DepartmentRatingDAL.Models.DataBase.Main", b =>
                {
                    b.HasOne("DepartmentRatingDAL.Models.DataBase.Offence", "Offence")
                        .WithMany("Main")
                        .HasForeignKey("OffenceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DepartmentRatingDAL.Models.DataBase.User", "User")
                        .WithMany("Main")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
